name: 'pnpm install with cache'
description: 'Speed up pnpm installation by caching pnpm store.'
author: 'Covbot'
branding:
    icon: 'box'
    color: 'yellow'
runs:
    using: composite
    steps:
        - name: Get pnpm store directory
          id: pnpm-cache
          shell: bash
          run: |
              echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

        - name: Setup pnpm cache
          uses: actions/cache@v3
          with:
              path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
              key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
              restore-keys: |
                  ${{ runner.os }}-pnpm-store-

        - name: Install dependencies
          run: pnpm install
          shell: bash
